### ISSUE TITLE
Update the updates files

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#92] opened 2016-03-09 16:13 UTC
Please update the following based on the recent commits to the master.
https://github.com/DIDSR/iMRMC/blob/master/UPDATES_iMRMC.md
https://github.com/DIDSR/iMRMC/blob/master/UPDATES_iRoeMetz.md

**Comment by qigongFDA** [comment] 2016-06-30 20:57
There are the updates for iMRMC and iRoeMetz. After final check, we could release new version.
[iRoeMetzUpdates.txt](https://github.com/DIDSR/iMRMC/files/342345/iRoeMetzUpdates.txt)
[imrmcUpdates.txt](https://github.com/DIDSR/iMRMC/files/342344/imrmcUpdates.txt)

**Comment by qigongFDA** [comment] 2016-10-04 15:04
Could we close this issue?

**Comment by qigongFDA** [comment] 2017-01-10 20:19
Brandon acknowledges the issue is fixed

**Closed by qigongFDA** 2017-01-10 20:19 UTC
